### PR TITLE
Use `string.format` to insert username in ldap query

### PR DESCRIPTION
**Pull request by ghost**
Hi Lucterios2,

I had the need to login against an active directory with using either sAMAccountName or userPrincipalName. To have the username inserted twice into the LDAP-query I replaced the % operator with `string.format`. This breaks the configuration as it is now. So I updated to `README.md` as well.

I don't know how you are dealing with versions so I put a 
> from version xxx on you should user (sAMAccountName={0}) ... 

to the part in README.

Additionally I changed the userlookup to use the mapped field from `LDAP_ATTRIBUTES_MAP` to find the correct user.

I hope you like this pull request.

Best Regards
Seyhbold

### CODE REVIEW

**Review by povtux — CHANGES_REQUESTED** [review]
Hi,
Your suggestion is good but I really would like to keep backwards compatibility. It's always disappointing when you just update a dependency and break you tool...

Could you please test the filter for the presence of "%s" or "{0}" and depending on witch is available, use the good way of formatting?

If you do that, I will be pleased to merge you request!

Regards,
Pierre-Olivier

**Comment by ghost** [comment]
Hi,

I have changed my branch to use a `string.replace('%s', '{0}')` before using format.
Additionally I changed the README.md

Do you think this is better?

Regards
Seyhbold

**Comment by ghost** [comment]
Hi, 

I'm not sure how you want the PR. I force pushed to the existing one. Or do you want me to create a new PR?

Best Regards
Seyhbold

**Review by povtux — APPROVED** [review]

**Comment by povtux** [comment]
Thanks for your job :)

**Comment by ghost** [comment]
Hi,

is there any chance to get this published to pypi?

Thank you very much
Regards
Seyhbold

**Pull request merged**
